### ISSUE TITLE
bug: the sidebar re renders when the while switching between videos

### ISSUE THREAD

**Issue by alexbennycodes** [code100x/cms#348]
https://github.com/code100x/cms/assets/98402835/7bace462-37f1-4daf-beb2-d439ad8501ce

**Comment by aakash2330** [comment]
🙋 @hkirat

**Comment by alexbennycodes** [comment]
@aakash2330 if u want u can work on the issue, its simple just move the sidebar component with the get api call to the layout.js file into courseId folder

**Comment by aakash-a-dev** [comment]
I need a little guidance, I added Sidebar in layout.tsx under [...courseId] > layout.tsx,
I am getting this error 
![image](https://github.com/code100x/cms/assets/126223325/145f2809-5222-402c-aa64-7443686f61ac)
This error coming under Sidebar.tsx
⨯ src\components\Sidebar.tsx (67:20) @ map
 ⨯ TypeError: Cannot read properties of undefined (reading 'map')
    at renderContent (./src/components/Sidebar.tsx:64:25)
    at Sidebar (./src/components/Sidebar.tsx:204:27)
  65 |
  66 |   const renderContent = (contents: any) => {
> 67 |     return contents.map((content: any) => {
     |                    ^
  68 |       if (content.children && content.children.length > 0) {
  69 |         // This is a folder with children
  70 |         return (
 ⨯ src\components\Sidebar.tsx (67:20) @ map
 ⨯ TypeError: Cannot read properties of undefined (reading 'map')
    at renderContent (./src/components/Sidebar.tsx:64:25)
    at Sidebar (./src/components/Sidebar.tsx:204:27)
  65 |
  66 |   const renderContent = (contents: any) => {
> 67 |     return contents.map((content: any) => {
     |                    ^
  68 |       if (content.children && content.children.length > 0) {
  69 |         // This is a folder with children
  70 |         return (

I can't find help on this will need how I can tackle

**Comment by alexbennycodes** [comment]
@aakash-a-dev the session is still in loading phase while the sidebar is being rendered, the response from the server will give unauthorized access, so the contents would be undefined, i guess

**Comment by aakash-a-dev** [comment]
I figured out that layout.tsx doesn't allow data fetching directly so going through documentation probable it can help me out

**Comment by alexbennycodes** [comment]
hey just checked the code out, its not that simple, i might also be working on it

**Comment by krishhh16** [comment]
I Think I'll try it out

**Comment by aakash2330** [comment]
https://github.com/code100x/cms/pull/349#issue-2233710666

**Comment by alexbennycodes** [comment]
@aakash2330 this PR does not fix the issue, it will still rerender, the issue i was talking about, is that when a user switches between different videos the sidebar should be fixed and the loader should only come at the place where the video is

**Comment by aakash-a-dev** [comment]
> hey just checked the code out, its not that simple as thought, i might also be working on it, feel free to give a shot

I am quite close to the solution just have to call the APIs in the layout I am stuck there, is it possible to work together on this?

**Comment by alexbennycodes** [comment]
@aakash-a-dev I'm done just creating the PR, you can take a look at it.

**Comment by aakash-a-dev** [comment]
> @aakash-a-dev I'm done just creating the PR, you can take a look at it.

Okayyy
